version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn clean test
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir artifacts;
            echo "my artifact file" > artifacts/artifact-1;
      - store_artifacts:
          path: artifacts
