version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn clean test
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir /home/circleci/repo/artifacts;
            echo "my artifact file" > /home/circleci/repo/artifacts/artifact-1;
      - store_artifacts:
          path: /home/circleci/repo/artifacts/artifact-1
