version: 2
orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
#    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn clean test
      - store_artifacts:
          path: screens
          destination: screens
          when: always