version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
#      - run:
#          name: run tests
#          command: |
#            mvn clean test
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir ~/repo/screens;
            echo "my artifact files in a dir" > ~/repo/screens/artifact-2;
      - store_artifacts:
          path: ~/repo/screens/artifact-2
          destination: artifact-file
