version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn clean test -X
      - store_artifacts:
          path: ~/repo/screens/screenshot.png
          destination: artifact-file
