version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
#      - run:
#          name: run tests
#          command: |
#            mvn clean test
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > ~/repo/sreens/artifact-1;
      - store_artifacts:
          path: ~/repo/sreens
          destination: artifact-file
