version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
#      - run:
#          name: run tests
#          command: |
#            mvn clean test
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > ~/repo/artifact-1;
            mkdir ~/repo/artifacts;
            echo "my artifact files in a dir" > ~/repo/artifacts/artifact-2;
      - store_artifacts:
          path: ~/repo/artifact-1
          destination: artifact-file
