version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-stretch-browsers
#    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn clean test
      - store_artifacts:
          path: D:\Courses\Java\HomeWork_UI\screens
          destination: D:\Courses\Java\HomeWork_UI\screens
          when: always